version: "3"
services:
  prestashop:
    image: prestashop/prestashop
    volumes:
      - ./data:/var/www/html
    ports:
      - "8080:80"
    restart: unless-stopped
  DB:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=bd_cristobal
      - MYSQL_USER=bd_cristobal
      - MYSQL_PASSWORD=bd_cristobal
      - MYSQL_ROOT_PASSWORD=bd_cristobal
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
   driver: local
  data:
   driver: local
