<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEumpeci\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEumpeci/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEumpeci.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEumpeci\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEumpeci\appProdProjectContainer([
    'container.build_hash' => 'Eumpeci',
    'container.build_id' => 'e09125ef',
    'container.build_time' => 1620968774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEumpeci');
